server:
  port: 8801
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: wayne-generate
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/pear-admin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456
# Mybatis 配 置
mybatis:
  # 配 置 扫 描
  mapper-locations: classpath*:**/xml/**.xml
  # 别 名 扫 描
  type-aliases-package: com.wayne.generate
wayne:
  swagger:
    # 文 档 标 题
    title: Wayne Admin API
    # 是 否 开 启
    enable: true
    # 描 述 信 息
    describe: 企 业 快 速 开 发 平 台
    # 扫 包 路 径
    scan-package: com.wayne.generate
    # 协 议
    licence: MIT
    # 协 议 地 址
    licence-url: https://gitee.com/pear_community
    # 组 织 信 息
    terms-of-service-url: https://gitee.com/pear_community
    # 版 本 信 息
    version: Release 2.0.0
    # 扩 展 信 息
    contact:
      # 作 者
      name: 就 眠 仪 式
      # 连 接
      url: www.pearadmin.cn
      # 邮 箱
      email: Jmys1992@gmail.com