auth-host: http://sso.local.wayne.com:8801
auth-path: wayne-web
#auth-host: http://sso.dev.bj.iquantex.com
#auth-path: portal-auth
gateway-host: http://wayne-gateway.local.wayne.com:8080
# portal 首页访问地址
portal-url: http://wayne-gateway.local.wayne.com:8080

spring:
  application:
    name: wayne-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          #服务ID转小写
          lower-case-service-id: true
          #开启自动发现服务
          enabled: true
      routes:
        - id: product-service-limiter
          uri: lb://nacos-discovery-product
          predicates:
            - Path=/product/**
          filters:
            # 令牌桶算法限流
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 5
                keyResolver: '#{@myKeyResolver}'
            # 熔断过滤器 访问错误跳转到网关的 /downgrade接口
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/downgrade
            # 自定义网关过滤器
            - name: RequestPath
              args:
                name: key
                path: value
  #redis缓存
  redis:
    timeout: 10000          #连接超时时间
    host: 192.168.16.10     #Redis 服务地址
    port: 6379              #Redis 端口
    database: 0             #使用的库 默认0库
    lettuce:
      pool:
        max-active: 1024    #最大连接数 默认8
        max-wait: 1000      #最大连接阻塞等待时间，单位毫秒 默认-1
        max-idle: 200       #最大空闲连接数 默认8
        min-idle: 5         #最小空闲连接数 默认0
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: uaa
            client-id: wayne_gateway
            client-secret: changeit
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/${spring.application.name}/login/oauth2/code/{registrationId}"
            scope: api-read,api-write
        provider:
          uaa:
            authorization-uri: ${auth-host}/${auth-path}/oauth/authorize
            token-uri: ${auth-host}/${auth-path}/oauth/token
            user-info-uri: ${auth-host}/${auth-path}/api/userinfo
            user-name-attribute: sub
            jwk-set-uri: ${auth-host}/${auth-path}/.well-known/jwks.json
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
nacos:
  gateway:
    route:
      config:
        data-id: wayne-gateway-router
        group: DEFAULT_GROUP
wayne:
  sso:
    cookie-domain: local.wayne.com
    cookie-timeout-seconds: 8640000
    enabled: true
    login-success: /wayne-web
    logout-success: ${auth-host}/${auth-path}/logout?service=${gateway-host:http://wayne-gateway.local.wayne.com:8080}/${spring.application.name}