server:
  port: 8808
  servlet:
    # Session
    session:
      # 超 时 时 间
      timeout: 120m
    context-path: /web
spring:
  application:
    name: wayne-web
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: dev
        username: nacos
        password: nacos
  #redis缓存
  redis:
    timeout: 10000          #连接超时时间
    host: 192.168.16.128    #Redis 服务地址
    port: 6379              #Redis 端口
    database: 0             #使用的库 默认0库
    lettuce:
      pool:
        max-active: 1024    #最大连接数 默认8
        max-wait: 1000      #最大连接阻塞等待时间，单位毫秒 默认-1
        max-idle: 200       #最大空闲连接数 默认8
        min-idle: 5         #最小空闲连接数 默认0
wayne:
  swagger:
    # 文 档 标 题
    title: Wayne Admin API
    # 是 否 开 启
    enable: true
    # 描 述 信 息
    describe: 企 业 快 速 开 发 平 台
    # 扫 包 路 径
    scan-package: com.wayne.web
    # 协 议
    licence: MIT
    # 协 议 地 址
    licence-url: https://gitee.com/pear_community
    # 组 织 信 息
    terms-of-service-url: https://gitee.com/pear_community
    # 版 本 信 息
    version: Release 2.0.0
    # 扩 展 信 息
    contact:
      # 作 者
      name: 就 眠 仪 式
      # 连 接
      url: www.pearadmin.cn
      # 邮 箱
      email: Jmys1992@gmail.com
  # 权 限 配 置
  security:
    # 开 启 超 级 管 理 员 账 号 -- 不需要验证权限
    super-auth-open: true
    # 超 级 管 理 员 账 号 -- 不需要验证权限
    super-admin: admin
logging:
  level:
    root: info